name: Security and Deprecation Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Verificar estrutura de pastas
        run: |
          pwd
          ls -la
          ls -la src/

      # Configurar PHP 8.3.16
      - name: Configurar versão do PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3.16

      - name: Instalar dependências Node.js
        working-directory: ./src
        run: npm ci

      - name: Instalar dependências PHP
        working-directory: ./src
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Rodar Snyk para todos os projetos
        if: github.actor != 'dependabot[bot]'
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --all-projects --detection-depth=3 --severity-threshold=medium --fail-on=all
          project: ./src

      - name: Verificar estilo de código com Laravel Pint
        working-directory: ./src
        run: ./vendor/bin/pint --test

      - name: Verificar código Vue/JS com ESLint
        working-directory: ./src
        run: npx eslint resources/js --ext .js,.vue --max-warnings=0

      - name: Verificar código PHP com Psalm
        working-directory: ./src
        run: |
          if [ ! -f psalm.xml ]; then ./vendor/bin/psalm --init; fi
          ./vendor/bin/psalm

      - name: Verificar código PHP com PHPStan
        working-directory: ./src
        run: |
          if [ ! -f phpstan.neon ]; then ./vendor/bin/phpstan init; fi
          ./vendor/bin/phpstan analyse --memory-limit=2G --configuration=phpstan.neon --level=max .
