name: OWASP Dependency-Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Instalar dependências Node.js
        run: npm install

      - name: Instalar dependências PHP
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Rodar OWASP Dependency-Check via Docker
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          docker run --rm \
            -e NVD_API_KEY="${NVD_API_KEY}" \
            -v ${{ github.workspace }}:/src \
            owasp/dependency-check \
            --project "Laravel + Vue Project" \
            --scan /src \
            --format HTML \
            --out /src/reports \
            --nvdApiKey "$NVD_API_KEY"

      - name: Publicar Relatório como Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports
