name: OWASP Dependency-Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Rodar OWASP Dependency-Check via Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            owasp/dependency-check \
            --project "Laravel + Vue" \
            --scan /src \
            --format HTML \
            --out /src/reports

      - name: Publicar Relatório como Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports
