name: Security and Deprecation Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      # Clonar o repositório
      - name: Checkout código
        uses: actions/checkout@v3

      # Instalar dependências Node.js
      - name: Instalar dependências Node.js
        run: npm ci

      # Instalar dependências PHP
      - name: Instalar dependências PHP
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # Rodar Snyk
      - name: Rodar Snyk para todos os projetos
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --all-projects --detection-depth=3 --severity-threshold=medium --fail-on=all

      # Verificar código PHP deprecado com Psalm
      - name: Verificar código PHP com Psalm
        run: |
          if [ ! -f psalm.xml ]; then ./vendor/bin/psalm --init; fi
          ./vendor/bin/psalm

      # Verificar código JS/Vue com ESLint
      - name: Verificar código JS/Vue com ESLint
        run: npx eslint resources/js
